// Pure (DOM-free) comparison of two whole documents, used by the import
// confirmation modal so an import isn't a blind "replaces your current data".
// Keep this DOM-free like time.js — it's the piece worth testing.
import { DAY_SHORT, formatTime12 } from "./time.js";
import { CATEGORIES } from "./schema.js";

const CATEGORY_LABELS = Object.fromEntries(CATEGORIES.map((c) => [c.key, c.label]));

// Fields compared one-by-one and reported by name. `hours`/`exceptions` are
// handled separately (as sets, below) since they're arrays of objects.
const SCALAR_FIELDS = [
  ["name", "Name"],
  ["address", "Address"],
  ["phone", "Phone"],
  ["website", "Website"],
  ["notes", "Notes"],
  ["color", "Color"],
];

export function describeHour(h) {
  const label = h.label ? ` (${h.label})` : "";
  return `${DAY_SHORT[h.dayOfWeek] ?? "?"} ${formatTime12(h.start)}–${formatTime12(h.end)}${label}`;
}

export function describeException(e) {
  if (e.closed) return `${e.date}: closed${e.note ? ` (${e.note})` : ""}`;
  const window = e.start && e.end ? `${formatTime12(e.start)}–${formatTime12(e.end)}` : "no hours set";
  return `${e.date}: ${window}${e.note ? ` (${e.note})` : ""}`;
}

function categoryText(keys) {
  return (keys || []).map((k) => CATEGORY_LABELS[k] || k).sort().join(", ") || "(none)";
}

// Compare arrays of objects as multisets of their human-readable form rather
// than by id: ids are regenerated by hand-edited or third-party files, and
// "Tue 9AM–5PM was removed" is what the user actually wants to read.
function diffDescribed(a, b, describe) {
  const before = (a || []).map(describe);
  const after = (b || []).map(describe);
  const remaining = [...after];
  const removed = [];
  before.forEach((s) => {
    const at = remaining.indexOf(s);
    if (at === -1) removed.push(s);
    else remaining.splice(at, 1);
  });
  return { added: remaining.sort(), removed: removed.sort() };
}

function diffBusiness(before, after) {
  const changes = [];

  SCALAR_FIELDS.forEach(([key, label]) => {
    const a = before[key] || "";
    const b = after[key] || "";
    if (a !== b) changes.push({ field: label, before: a || "(empty)", after: b || "(empty)" });
  });

  const catBefore = categoryText(before.categories);
  const catAfter = categoryText(after.categories);
  if (catBefore !== catAfter) changes.push({ field: "Categories", before: catBefore, after: catAfter });

  const hours = diffDescribed(before.hours, after.hours, describeHour);
  const exceptions = diffDescribed(before.exceptions, after.exceptions, describeException);

  return { changes, hours, exceptions };
}

function hasBusinessChanges(d) {
  return d.changes.length > 0 || d.hours.added.length > 0 || d.hours.removed.length > 0
    || d.exceptions.added.length > 0 || d.exceptions.removed.length > 0;
}

// Match by id first (same-app exports keep ids stable), then fall back to a
// case-insensitive name match so a hand-rebuilt file still reads as an edit
// of an existing business rather than a remove + add pair.
function pair(current, incoming) {
  const pairs = [];
  const unmatchedIncoming = [...incoming];
  const removed = [];

  current.forEach((biz) => {
    let at = unmatchedIncoming.findIndex((b) => b.id && b.id === biz.id);
    if (at === -1) {
      at = unmatchedIncoming.findIndex((b) => (b.name || "").trim().toLowerCase() === (biz.name || "").trim().toLowerCase());
    }
    if (at === -1) removed.push(biz);
    else pairs.push([biz, unmatchedIncoming.splice(at, 1)[0]]);
  });

  return { pairs, added: unmatchedIncoming, removed };
}

// Returns a plain description of what importing `incoming` would do to
// `current`. Both are expected to already be migrate()d documents.
export function diffStates(current, incoming) {
  const { pairs, added, removed } = pair(current.businesses || [], incoming.businesses || []);

  const changed = pairs
    .map(([before, after]) => ({ before, after, ...diffBusiness(before, after) }))
    .filter(hasBusinessChanges);

  const filters = [];
  const filterKeys = new Set([
    ...Object.keys(current.categoryFilters || {}),
    ...Object.keys(incoming.categoryFilters || {}),
  ]);
  filterKeys.forEach((key) => {
    const a = (current.categoryFilters || {})[key] !== false;
    const b = (incoming.categoryFilters || {})[key] !== false;
    if (a !== b) filters.push({ label: CATEGORY_LABELS[key] || key, before: a, after: b });
  });

  const unchangedCount = pairs.length - changed.length;

  return {
    added,
    removed,
    changed,
    filters,
    unchangedCount,
    isNoop: !added.length && !removed.length && !changed.length && !filters.length,
  };
}
